sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "djordjebatic"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./mvnw clean install -DskipTests=false -B
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=djordjebatic_PSW-2019-2020-backend2

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: PSW-2019-2020-backend
